### ISSUE TITLE
你好，给的SOSpth文件是错的，能重新上传一个吗

### ISSUE THREAD

**Issue by liushh39** [qianxuanhu/SOSMaskFuse#1]

**Comment by qianxuanhu** [comment]
训练模型时候用hrnetv2_w30_imagenet_pretrained.pth。
测试融合效果用normal_epoch_170.pth
哪个文件有问题？

**Comment by ZZZengggg** [comment]
作者您好，请问可以提供一下hrnetv2_w30_imagenet_pretrained.pth、normal_epoch_170.pth文件吗
